<a href="https://colab.research.google.com/github/FGalvao77/-DICAS-Uso-de-ferramentas-para-Data-Science-e-afins/blob/main/%5BDICAS%5D_Construindo_um_Pipeline_b%C3%A1sico_de_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **[DICAS] - Construindo um `Pipeline` básico de _ML_**
---
---

In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split as tts
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error as mae

In [2]:
data = load_boston()

print(data.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [3]:
df = pd.DataFrame(
    data=data.data,
    columns=data.feature_names
)

df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [4]:
df['MEDV'] = data.target

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [5]:
df.describe().T

count        mean         std        min         25%        50%  \
CRIM     506.0    3.613524    8.601545    0.00632    0.082045    0.25651   
ZN       506.0   11.363636   23.322453    0.00000    0.000000    0.00000   
INDUS    506.0   11.136779    6.860353    0.46000    5.190000    9.69000   
CHAS     506.0    0.069170    0.253994    0.00000    0.000000    0.00000   
NOX      506.0    0.554695    0.115878    0.38500    0.449000    0.53800   
RM       506.0    6.284634    0.702617    3.56100    5.885500    6.20850   
AGE      506.0   68.574901   28.148861    2.90000   45.025000   77.50000   
DIS      506.0    3.795043    2.105710    1.12960    2.100175    3.20745   
RAD      506.0    9.549407    8.707259    1.00000    4.000000    5.00000   
TAX      506.0  408.237154  168.537116  187.00000  279.000000  330.00000   
PTRATIO  506.0   18.455534    2.164946   12.60000   17.400000   19.05000   
B        506.0  356.674032   91.294864    0.32000  375.377500  391.44000   
LSTAT    506.0   12.653063    7.141062    1.73000    6.950000   11.36000   
MEDV     506.0   22.532806    9.197104    5.00000   17.025000   21.20000   

                75%       max  
CRIM       3.677083   88.9762  
ZN        12.500000  100.0000  
INDUS     18.100000   27.7400  
CHAS       0.000000    1.0000  
NOX        0.624000    0.8710  
RM         6.623500    8.7800  
AGE       94.075000  100.0000  
DIS        5.188425   12.1265  
RAD       24.000000   24.0000  
TAX      666.000000  711.0000  
PTRATIO   20.200000   22.0000  
B        396.225000  396.9000  
LSTAT     16.955000   37.9700  
MEDV      25.000000   50.0000

In [6]:
X = df.iloc[:, :-1]

X[:5]

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [7]:
y = df.iloc[:, -1]

y[:5]

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64

In [8]:
Xtrain, Xval, yTrain, yVal = tts(
    X, y, test_size=0.5, random_state=0
)

Xtrain.shape, Xval.shape, yTrain.shape, yVal.shape

((253, 13), (253, 13), (253,), (253,))

In [9]:
steps = [
    ('scaler', StandardScaler()),
    ('LR', LinearRegression())
]

steps

[('scaler', StandardScaler()), ('LR', LinearRegression())]

In [10]:
pipe = Pipeline(steps)

pipe

Pipeline(steps=[('scaler', StandardScaler()), ('LR', LinearRegression())])

In [11]:
pipe.fit(Xtrain, yTrain)

Pipeline(steps=[('scaler', StandardScaler()), ('LR', LinearRegression())])

In [12]:
yPred = pipe.predict(Xval)

yPred[:5]

array([24.70960325, 25.12631354, 30.76503263, 12.41405512, 21.29599499])

In [13]:
print(f'Mean absolute error [Linear Regression]: {round(mae(yVal, yPred), 4)}')

Mean absolute error [Linear Regression]: 3.6278


In [14]:
steps_2 = [
    ('scaler', StandardScaler()),
    ('RF', RandomForestRegressor(n_estimators=250, n_jobs=-1, random_state=0))
]

steps_2

[('scaler', StandardScaler()),
 ('RF', RandomForestRegressor(n_estimators=250, n_jobs=-1, random_state=0))]

In [15]:
pipe_2 = Pipeline(steps_2)

pipe_2

Pipeline(steps=[('scaler', StandardScaler()),
                ('RF',
                 RandomForestRegressor(n_estimators=250, n_jobs=-1,
                                       random_state=0))])

In [16]:
pipe_2.fit(Xtrain, yTrain)

Pipeline(steps=[('scaler', StandardScaler()),
                ('RF',
                 RandomForestRegressor(n_estimators=250, n_jobs=-1,
                                       random_state=0))])

In [17]:
yPred_2 = pipe_2.predict(Xval)

yPred_2[:5]

array([23.6064, 24.6896, 22.1712, 10.2428, 20.51  ])

In [18]:
print(f'Mean absolute error [Random Forest]: {round(mae(yVal, yPred_2), 4)}')

Mean absolute error [Random Forest]: 2.4191


In [19]:
steps_3 = [
    ('scaler', StandardScaler()),
    ('XB Boost', XGBRegressor(n_estimators=250, n_jobs=-1, 
                              random_state=0, objective='reg:squarederror'))
]

steps_3

[('scaler', StandardScaler()),
 ('XB Boost',
  XGBRegressor(n_estimators=250, n_jobs=-1, objective='reg:squarederror'))]

In [20]:
pipe_3 = Pipeline(steps_3)

pipe_3

Pipeline(steps=[('scaler', StandardScaler()),
                ('XB Boost',
                 XGBRegressor(n_estimators=250, n_jobs=-1,
                              objective='reg:squarederror'))])

In [21]:
pipe_3.fit(Xtrain, yTrain)

Pipeline(steps=[('scaler', StandardScaler()),
                ('XB Boost',
                 XGBRegressor(n_estimators=250, n_jobs=-1,
                              objective='reg:squarederror'))])

In [22]:
yPred_3 = pipe_3.predict(Xval)

yPred_3[:5]

array([23.952936, 26.613625, 23.340595,  9.873569, 20.361511],
      dtype=float32)

In [23]:
print(f'Mean absolute error [XG Boost]: {round(mae(yVal, yPred_3), 4)}')

Mean absolute error [XG Boost]: 2.4246


In [24]:
steps_4 = [
    ('scaler', StandardScaler()),
    ('MLP', MLPRegressor(hidden_layer_sizes=(len(X), int(len(X)/2), int(len(X)/4)), 
                         max_iter=1_000, learning_rate='adaptive', random_state=0, solver='adam',))
]

steps_4

[('scaler', StandardScaler()),
 ('MLP',
  MLPRegressor(hidden_layer_sizes=(506, 253, 126), learning_rate='adaptive',
               max_iter=1000, random_state=0))]

In [25]:
pipe_4 = Pipeline(steps_4)

pipe_4

Pipeline(steps=[('scaler', StandardScaler()),
                ('MLP',
                 MLPRegressor(hidden_layer_sizes=(506, 253, 126),
                              learning_rate='adaptive', max_iter=1000,
                              random_state=0))])

In [26]:
pipe_4.fit(Xtrain, yTrain)

Pipeline(steps=[('scaler', StandardScaler()),
                ('MLP',
                 MLPRegressor(hidden_layer_sizes=(506, 253, 126),
                              learning_rate='adaptive', max_iter=1000,
                              random_state=0))])

In [27]:
yPred_4 = pipe_4.predict(Xval)

yPred_4[:5]

array([22.04949515, 29.5929229 , 26.48452713, 10.65307499, 20.03546647])

In [28]:
print(f'Mean absolute error [MLP]: {round(mae(yVal, yPred_4), 4)}')

Mean absolute error [MLP]: 2.2709
